security:
  auth:
    anonymous:
      enabled: true

  rbac:
    enabled: true
    rules:
    - title: all
      entity: anonymous
      verbs:
      - list
      - read
      - write
      - upload
      - edit
      - delete
      - download
      resources:
      - {}

storage:
  auth:
  - name: root
    basic:
      accessKey: root
      secretKey: ${SECRET_KEY}

  endpoints:
  - name: minio
    host: minio
    port: 9000
    protocol: http

  buckets:
  - title: Minio S3
    endpoint: minio
    region: us-east-1
    name: ${BUCKET}
    auth: root

  - title: Local FS
    path: /home/node
    name: home-node
