version: '2'

services:

  app:
    build:
      context: .
      dockerfile: ./packages/docker/Dockerfile
    environment:
    - GUI_PORT=8080
    - GUI_PUBLIC_DIR=/home/node/public
    - GUI_CONFIG_FILE=/home/node/config.yaml
    - BUCKET=gui
    - SECRET_KEY=rootroot
    ports:
    - 8080:8080
    volumes:
    - ./config.yaml:/home/node/config.yaml

  minio:
    image: bitnami/minio:2022.9.17
    ports:
    - 9000:9000
    volumes:
    - 'minio_data:/data'
    environment:
    - MINIO_ROOT_USER=root
    - MINIO_ROOT_PASSWORD=rootroot
    - MINIO_ACCESS_KEY=gui
    - MINIO_SECRET_KEY=rootroot
    - MINIO_DEFAULT_BUCKETS=gui
    - BITNAMI_DEBUG=true
volumes:
  minio_data:
    driver: local