security:
  auth:
    anonymous:
      enabled: true

  rbac:
    enabled: true
    rules:
    - title: base rule
      entity:
        kind: anonymous
        name: anonymous
      verbs:
      - list
      - read
      resources:
      - host: "(.*)"
        bucket: "(.*)"
    - title: allow edit/download for gui bucket
      entity:
        kind: anonymous
        name: anonymous
      verbs:
      - edit
      - download
      resources:
      - bucket: "gui"
    - title: upload/delete only on "Bucket/" prefix
      entity:
        kind: anonymous
        name: anonymous
      verbs:
      - delete
      - upload
      resources:
      - bucket: "gui"
        path: "^Bucket/(.*)$"
    - entity:
        kind: anonymous
        name: anonymous
      verbs:
      - list
      - read
      resources:
      - host: "(.*)prod(.*)"
        bucket: "(.*)"

storage:
  auth:
  - name: root
    basic:
      accessKey: root
      secretKey: rootroot

  - name: infra
    basic:
      accessKey: ${GUI_S3_ACCESS_KEY:}
      secretKey: ${GUI_S3_SECRET_KEY:}

  endpoints:
  - name: local
    host: localhost
    port: 9000
    protocol: http

  - name: infra
    host: ${GUI_S3_ENDPOINT:}
    port: 8080
    protocol: http

  buckets:
  - endpoint: local
    region: us-east-1
    name: gui
    auth: root
    title: gui as root

  - endpoint: infra
    region: us-east-1
    name: datahub-events
    auth: infra
    title: datahub
