apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gui.fullname" . }}-config
  labels:
    {{- include "gui.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- .Values.gui.config | nindent 4 -}}