apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gui.fullname" . }}
  labels:
    {{- include "gui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "gui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gui.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        configchecksum: {{ include (print .Template.BasePath "/config-cm.yaml") . | sha256sum | trunc 63 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gui.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.gui.listenPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          env:
          - name: GUI_CONFIG_FILE
            value: /mnt/gui/config.yaml
          - name: GUI_PORT
            value: "{{ .Values.gui.listenPort }}"
          - name: GUI_PUBLIC_DIR
            value: /home/node/public
          - name: GUI_PUBLIC_URL
            value: {{ .Values.gui.publicURL }}
          {{- with .Values.extraEnvs }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.extraEnvsOverrides }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          volumeMounts:
          - name: gui-config
            mountPath: /mnt/gui
          {{- with .Values.extraVolumeMounts }}
          {{ toYaml . | nindent 10 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: gui-config
        configMap:
          name: {{ include "gui.fullname" . }}-config
      {{- with .Values.extraVolumes }}
        {{ toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
