{{- if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "gui.fullname" . }}
  labels:
    {{- include "gui.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
        {{- include "gui.selectorLabels" . | nindent 6 }}
  ingress:
  - ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
  {{- with .Values.networkPolicy.egress }}
  egress:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
{{- end }}